application:
  refresh_interval: 300
  title: Dashboard de Pedidos Pendientes

database:
  charset: WIN1252
  driver: Firebird
  dsn: localhost:C:/microsip datos/forticlean.fdb
  password: 050587
  query: |
    SELECT 
      p.folio AS pedido,
      c.NOMBRE AS cliente,
      p.FECHA AS fecha,
      p.HORA AS hora,
      v.NOMBRE AS vendedora,
      p.ESTATUS AS estatus
    FROM 
      DOCTOS_VE p
      LEFT JOIN CLIENTES c ON p.CLIENTE_ID = c.CLIENTE_ID
      LEFT JOIN VENDEDORES v ON p.VENDEDOR_ID = v.VENDEDOR_ID
    WHERE 
      p.tipo_docto = 'P' 
      AND (
        p.ESTATUS = 'P'  
        OR (p.ESTATUS = 'S' AND p.FECHA = CURRENT_DATE)
      )
    ORDER BY 
      p.ESTATUS, p.FECHA DESC, p.HORA DESC
  user: SYSDBA

users:
  admin:
    is_superadmin: true
    password: pbkdf2:sha256:150000$q8DNDrQw$eaa2a4e8d583e6e756a83c6e4feece1011d363d3489efe677cbba33c8fc77c24
    role: superadmin
  usuario:
    is_superadmin: false
    password: pbkdf2:sha256:150000$q8DNDrQw$eaa2a4e8d583e6e756a83c6e4feece1011d363d3489efe677cbba33c8fc77c24
    role: user
