application:
  refresh_interval: 300
  title: Dashboard de Pedidos Pendientes
database:
  charset: WIN1252
  driver: Firebird
  dsn: localhost:C:/Microsip/EMPRESA.FDB
  password: masterkey
  query: "SELECT \n  p.PEDIDO AS pedido,\n  c.NOMBRE AS cliente,\n  p.FECHA AS fecha,\n\
    \  p.HORA AS hora,\n  v.NOMBRE AS vendedora,\n  p.ESTATUS AS estatus\nFROM \n\
    \  PEDIDOS p\nJOIN \n  CLIENTES c ON p.CLIENTE_ID = c.CLIENTE_ID\nJOIN\n  VENDEDORES\
    \ v ON p.VENDEDOR_ID = v.VENDEDOR_ID\nWHERE \n  p.ESTATUS = 'P' OR p.ESTATUS =\
    \ 'En proceso'\nORDER BY \n  p.FECHA DESC, p.HORA DESC\n"
  user: SYSDBA
users:
  admin:
    is_superadmin: true
    password: pbkdf2:sha256:150000$q8DNDrQw$eaa2a4e8d583e6e756a83c6e4feece1011d363d3489efe677cbba33c8fc77c24
    role: superadmin
  usuario:
    is_superadmin: false
    password: pbkdf2:sha256:150000$q8DNDrQw$eaa2a4e8d583e6e756a83c6e4feece1011d363d3489efe677cbba33c8fc77c24
    role: user
