-- Script SQL para crear una estructura similar a Microsip
-- Este script puede ayudar a probar la conexión con una base de datos de prueba

-- Crear tablas básicas
CREATE TABLE CLIENTES (
    CLIENTE_ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    RFC VARCHAR(20),
    DIRECCION VARCHAR(200),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100)
);

CREATE TABLE VENDEDORES (
    VENDEDOR_ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CLAVE VARCHAR(10),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100)
);

CREATE TABLE PEDIDOS (
    PEDIDO INTEGER NOT NULL PRIMARY KEY,
    CLIENTE_ID INTEGER NOT NULL,
    VENDEDOR_ID INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    ESTATUS CHAR(1) NOT NULL,
    TOTAL DECIMAL(15,2),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES(VENDEDOR_ID)
);

-- Crear secuencias para IDs
CREATE SEQUENCE GEN_CLIENTE_ID;
CREATE SEQUENCE GEN_VENDEDOR_ID;
CREATE SEQUENCE GEN_PEDIDO_ID;

-- Insertar datos de muestra para clientes
INSERT INTO CLIENTES (CLIENTE_ID, NOMBRE, RFC, DIRECCION, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_CLIENTE_ID, 'Distribuidora El Norte', 'XAXX010101000', 'Av. Principal 123', '871-123-4567', 'contacto@elnorte.com');

INSERT INTO CLIENTES (CLIENTE_ID, NOMBRE, RFC, DIRECCION, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_CLIENTE_ID, 'Supermercados González', 'GOXX871210ABC', 'Blvd. Independencia 456', '871-765-4321', 'compras@sgonzalez.com');

INSERT INTO CLIENTES (CLIENTE_ID, NOMBRE, RFC, DIRECCION, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_CLIENTE_ID, 'Tiendas Laguna', 'TLXX980517XXX', 'Calle Matamoros 789', '871-987-6543', 'pedidos@tiendaslaguna.com');

INSERT INTO CLIENTES (CLIENTE_ID, NOMBRE, RFC, DIRECCION, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_CLIENTE_ID, 'Comercial del Bajío', 'CBXX030405XXX', 'Periférico 200', '477-123-9876', 'info@comercialbajio.com');

INSERT INTO CLIENTES (CLIENTE_ID, NOMBRE, RFC, DIRECCION, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_CLIENTE_ID, 'Refaccionaria Torreón', 'RTXX121212XXX', 'Diagonal Reforma 333', '871-222-3333', 'ventas@refaccionestorreon.com');

-- Insertar datos de muestra para vendedores
INSERT INTO VENDEDORES (VENDEDOR_ID, NOMBRE, CLAVE, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_VENDEDOR_ID, 'María López', 'ML001', '871-111-2222', 'maria@cliclaguna.com');

INSERT INTO VENDEDORES (VENDEDOR_ID, NOMBRE, CLAVE, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_VENDEDOR_ID, 'Juan Pérez', 'JP002', '871-222-3333', 'juan@cliclaguna.com');

INSERT INTO VENDEDORES (VENDEDOR_ID, NOMBRE, CLAVE, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_VENDEDOR_ID, 'Ana Morales', 'AM003', '871-333-4444', 'ana@cliclaguna.com');

INSERT INTO VENDEDORES (VENDEDOR_ID, NOMBRE, CLAVE, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_VENDEDOR_ID, 'Carlos Sánchez', 'CS004', '871-444-5555', 'carlos@cliclaguna.com');

INSERT INTO VENDEDORES (VENDEDOR_ID, NOMBRE, CLAVE, TELEFONO, EMAIL)
VALUES (NEXT VALUE FOR GEN_VENDEDOR_ID, 'Laura Torres', 'LT005', '871-555-6666', 'laura@cliclaguna.com');

-- Insertar datos de muestra para pedidos
-- Estatus: P = Pendiente, E = En proceso, T = Terminado
-- Fecha y Hora actuales
INSERT INTO PEDIDOS (PEDIDO, CLIENTE_ID, VENDEDOR_ID, FECHA, HORA, ESTATUS, TOTAL)
VALUES (2501, 1, 1, CURRENT_DATE - 1, '09:15:22', 'P', 12500.00);

INSERT INTO PEDIDOS (PEDIDO, CLIENTE_ID, VENDEDOR_ID, FECHA, HORA, ESTATUS, TOTAL)
VALUES (2502, 2, 2, CURRENT_DATE - 1, '10:05:45', 'E', 8750.50);

INSERT INTO PEDIDOS (PEDIDO, CLIENTE_ID, VENDEDOR_ID, FECHA, HORA, ESTATUS, TOTAL)
VALUES (2503, 3, 3, CURRENT_DATE - 1, '11:30:12', 'P', 5200.75);

INSERT INTO PEDIDOS (PEDIDO, CLIENTE_ID, VENDEDOR_ID, FECHA, HORA, ESTATUS, TOTAL)
VALUES (2504, 4, 4, CURRENT_DATE, '08:45:07', 'P', 15800.25);

INSERT INTO PEDIDOS (PEDIDO, CLIENTE_ID, VENDEDOR_ID, FECHA, HORA, ESTATUS, TOTAL)
VALUES (2505, 5, 5, CURRENT_DATE, '09:20:55', 'E', 3200.00);

COMMIT;